# Header
menu:
  首页: /
  友链: /links
  关于: /about
  说说: /message

# 主页banner图
banner: https://p.pstatp.com/origin/pgc-image/3bff83e0c7124df1bf18525e942a3080

# 站点通知信息
notice: 微信群组文档更新反馈请在企业微信文档表格中提交

# 作者信息
author:
  name: NOISE
  avatar: https://p.pstatp.com/origin/pgc-image/d387c226e6a84ae191485a46fc24eeba
  description: 学无止境

toc:
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: true
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: PMd59BNMA9UejPKUQnXvTnBp-gzGzoHsz
    appKey: BAESSxGaaul2Lrvs876IIObX
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: true
    visitor: true
    pageSize: 10
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: 
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: 
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: https://p.pstatp.com/origin/pgc-image/d6c4dad395c74f9e997b2a0390c88b5b


# Social Icon
social_icon:
  enable: false
  icons:
    ins     :
    zhihu   :
    weibo   : 
    github  : https://github.com/miiiku/
    twitter : https://twitter.com/guanquanhong

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 页脚第一行文字的 HTML，建议保留 Fluid 的链接，用于向更多人推广本主题
  # HTML of the first line of the footer, it is recommended to keep the Fluid link to promote this theme to more people
  content: '
    <div class="text-center py-1">   
  <div>
    <span>Copyright © 2021</span></a>
    <a href="https://noisesite.cn" target="_blank" rel="nofollow noopener">
     <span>Noise&自留地</span></a>    <br>
  </div>
  '


  # 版权声明，会显示在每篇文章的结尾
  # Copyright, will be displayed at the end of each post
  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 协议</a> ，转载请注明出处！'