# Header
menu:
  首页: /
  友链: /links
  关于: /about


# 主页banner图
banner: https://pic.ioiox.com/images/2021/11/02/0cd67b39fc4b1852a0d7506ff1a9a862.jpg

# 站点通知信息
notice: 感谢曾付出和愿意参与分享的朋友

# 作者信息
author:
  name: NOISE
  avatar: https://pic.ioiox.com/images/2021/11/02/6565b68f0490f7c21a56ddddac4813d4.jpg
  description: 热爱生活，忠于自己，付出每一帧每一秒，才能更懂得自己，更懂得生活

toc:
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: true
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: PMd59BNMA9UejPKUQnXvTnBp-gzGzoHsz
    appKey: BAESSxGaaul2Lrvs876IIObX
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: false
    visitor: false
    pageSize: 10
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: 
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: 
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: https://pic.ioiox.com/images/2021/11/02/e2f772963226271c00a98507a0d5044a.png


# Social Icon
social_icon:
  enable: false
  icons:
    ins     :
    zhihu   :
    weibo   : 
    github  : https://github.com/miiiku/
    twitter : https://twitter.com/guanquanhong

# 本地搜索
local_search:
  enable: true
  # if auto, trigger search by changing input

# if manual, trigger search by pressing enter key or search button

trigger: auto

# show top n results per article, show all results by setting to -1

top_n_per_article: 1
