name: Hexo Auto Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */6 * * * 
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: rcy1314
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: 1129159201@qq.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: rcy1314/quanshoulubook
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: gh-pages
  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:rcy1314/quanshoulubook.git
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node_version: [16.15.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update submodule
        run: git submodule update --remote    
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts
          git config --global user.name 'rcy1314'
          git config --global user.email '1129159201@qq.com'

      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
      
